name: Build docker image and push to docker hub on release

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
env:
  PLATFORMS: "linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/arm/v6"
  
jobs:
  build_and_push:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Extract tag string
        id: git
        shell: bash
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo "::set-output name=image_tag::${RELEASE_VERSION}"
          echo "Action image_tag=${RELEASE_VERSION}"
          
      - name: Login to docker hub
        uses: docker/login-action@v1.13.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Install buildx
        uses: docker/setup-buildx-action@v1.6.0
        
      - name: Build and push ${{ github.repository }}:${{ steps.git.outputs.image_tag }}
        uses: docker/build-push-action@v2.9.0
        with:
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: |
            ${{ github.repository }}:${{ steps.git.outputs.image_tag }}
            ${{ github.repository }}:latest

      - name: Update dockerhub description
        uses: peter-evans/dockerhub-description@v2.4.3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ github.repository }}
          short-description: ${{ github.event.repository.description }}
